name: Trigger Release

on:
  workflow_dispatch:
    inputs:
      release-version:
        description: 'The version with which the code should be released (e.g., 1.0.0)'
        type: string
        required: true
      post-release-version:
        description: 'The next snapshot version (e.g., 1.0.1-SNAPSHOT)'
        type: string
        required: true

jobs:
  trigger-release:
    runs-on: ubuntu-latest
    name: Trigger the release

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Set Git User and Email
        run: |
          git config --global user.email "no-reply@github-action.de"
          git config --global user.name "GitHub Action"

      - name: Run gradle release task
        run: |
          ./gradlew release -PreleaseVersion=${{ github.event.inputs.release-version }} -PpostReleaseVersion=${{ github.event.inputs.post-release-version }}

      - name: Push release changes
        run: |
          git push
          git push origin ${{ github.event.inputs.release-version }}
